disabled_rules:
- force_cast
- identifier_name
- line_length
- shorthand_operator
- trailing_whitespace
- type_name
- function_parameter_count
- function_body_length
- nesting
- cyclomatic_complexity


opt_in_rules:
- mark
type_body_length:
    - 1000
    - 1500

file_length:
    warning: 3000
    error: 4000
    
excluded:
- Kerdy/Application
